-- -------------------------------------------------------------
-- 
-- File Name: hdl_32bits\hdlsrc\fec_ber_hw_V2\qam_mapping_src_N_Width_QAM_16_Symbol_Mapping_Imag.vhd
-- Created: 2022-10-27 12:38:09
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: qam_mapping_src_N_Width_QAM_16_Symbol_Mapping_Imag
-- Source Path: fec_ber_hw_V2/QAM Mapping/QAM Mapping/N-Width QAM-16 Symbol Mapping Imag
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY qam_mapping_src_N_Width_QAM_16_Symbol_Mapping_Imag IS
  PORT( bits                              :   IN    std_logic_vector(63 DOWNTO 0);  -- ufix64
        symbol                            :   OUT   std_logic_vector(47 DOWNTO 0)  -- ufix48
        );
END qam_mapping_src_N_Width_QAM_16_Symbol_Mapping_Imag;


ARCHITECTURE rtl OF qam_mapping_src_N_Width_QAM_16_Symbol_Mapping_Imag IS

  -- Component Declarations
  COMPONENT qam_mapping_src_QAM_16_Symbol_Mapping_0
    PORT( bits                            :   IN    std_logic_vector(63 DOWNTO 0);  -- ufix64
          Q                               :   OUT   std_logic_vector(2 DOWNTO 0)  -- sfix3
          );
  END COMPONENT;

  COMPONENT qam_mapping_src_QAM_16_Symbol_Mapping_1
    PORT( bits                            :   IN    std_logic_vector(63 DOWNTO 0);  -- ufix64
          Q                               :   OUT   std_logic_vector(2 DOWNTO 0)  -- sfix3
          );
  END COMPONENT;

  COMPONENT qam_mapping_src_QAM_16_Symbol_Mapping_2
    PORT( bits                            :   IN    std_logic_vector(63 DOWNTO 0);  -- ufix64
          Q                               :   OUT   std_logic_vector(2 DOWNTO 0)  -- sfix3
          );
  END COMPONENT;

  COMPONENT qam_mapping_src_QAM_16_Symbol_Mapping_3
    PORT( bits                            :   IN    std_logic_vector(63 DOWNTO 0);  -- ufix64
          Q                               :   OUT   std_logic_vector(2 DOWNTO 0)  -- sfix3
          );
  END COMPONENT;

  COMPONENT qam_mapping_src_QAM_16_Symbol_Mapping_4
    PORT( bits                            :   IN    std_logic_vector(63 DOWNTO 0);  -- ufix64
          Q                               :   OUT   std_logic_vector(2 DOWNTO 0)  -- sfix3
          );
  END COMPONENT;

  COMPONENT qam_mapping_src_QAM_16_Symbol_Mapping_5
    PORT( bits                            :   IN    std_logic_vector(63 DOWNTO 0);  -- ufix64
          Q                               :   OUT   std_logic_vector(2 DOWNTO 0)  -- sfix3
          );
  END COMPONENT;

  COMPONENT qam_mapping_src_QAM_16_Symbol_Mapping_6
    PORT( bits                            :   IN    std_logic_vector(63 DOWNTO 0);  -- ufix64
          Q                               :   OUT   std_logic_vector(2 DOWNTO 0)  -- sfix3
          );
  END COMPONENT;

  COMPONENT qam_mapping_src_QAM_16_Symbol_Mapping_7
    PORT( bits                            :   IN    std_logic_vector(63 DOWNTO 0);  -- ufix64
          Q                               :   OUT   std_logic_vector(2 DOWNTO 0)  -- sfix3
          );
  END COMPONENT;

  COMPONENT qam_mapping_src_QAM_16_Symbol_Mapping_8
    PORT( bits                            :   IN    std_logic_vector(63 DOWNTO 0);  -- ufix64
          Q                               :   OUT   std_logic_vector(2 DOWNTO 0)  -- sfix3
          );
  END COMPONENT;

  COMPONENT qam_mapping_src_QAM_16_Symbol_Mapping_9
    PORT( bits                            :   IN    std_logic_vector(63 DOWNTO 0);  -- ufix64
          Q                               :   OUT   std_logic_vector(2 DOWNTO 0)  -- sfix3
          );
  END COMPONENT;

  COMPONENT qam_mapping_src_QAM_16_Symbol_Mapping_10
    PORT( bits                            :   IN    std_logic_vector(63 DOWNTO 0);  -- ufix64
          Q                               :   OUT   std_logic_vector(2 DOWNTO 0)  -- sfix3
          );
  END COMPONENT;

  COMPONENT qam_mapping_src_QAM_16_Symbol_Mapping_11
    PORT( bits                            :   IN    std_logic_vector(63 DOWNTO 0);  -- ufix64
          Q                               :   OUT   std_logic_vector(2 DOWNTO 0)  -- sfix3
          );
  END COMPONENT;

  COMPONENT qam_mapping_src_QAM_16_Symbol_Mapping_12
    PORT( bits                            :   IN    std_logic_vector(63 DOWNTO 0);  -- ufix64
          Q                               :   OUT   std_logic_vector(2 DOWNTO 0)  -- sfix3
          );
  END COMPONENT;

  COMPONENT qam_mapping_src_QAM_16_Symbol_Mapping_13
    PORT( bits                            :   IN    std_logic_vector(63 DOWNTO 0);  -- ufix64
          Q                               :   OUT   std_logic_vector(2 DOWNTO 0)  -- sfix3
          );
  END COMPONENT;

  COMPONENT qam_mapping_src_QAM_16_Symbol_Mapping_14
    PORT( bits                            :   IN    std_logic_vector(63 DOWNTO 0);  -- ufix64
          Q                               :   OUT   std_logic_vector(2 DOWNTO 0)  -- sfix3
          );
  END COMPONENT;

  COMPONENT qam_mapping_src_QAM_16_Symbol_Mapping_15
    PORT( bits                            :   IN    std_logic_vector(63 DOWNTO 0);  -- ufix64
          Q                               :   OUT   std_logic_vector(2 DOWNTO 0)  -- sfix3
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : qam_mapping_src_QAM_16_Symbol_Mapping_0
    USE ENTITY work.qam_mapping_src_QAM_16_Symbol_Mapping_0(rtl);

  FOR ALL : qam_mapping_src_QAM_16_Symbol_Mapping_1
    USE ENTITY work.qam_mapping_src_QAM_16_Symbol_Mapping_1(rtl);

  FOR ALL : qam_mapping_src_QAM_16_Symbol_Mapping_2
    USE ENTITY work.qam_mapping_src_QAM_16_Symbol_Mapping_2(rtl);

  FOR ALL : qam_mapping_src_QAM_16_Symbol_Mapping_3
    USE ENTITY work.qam_mapping_src_QAM_16_Symbol_Mapping_3(rtl);

  FOR ALL : qam_mapping_src_QAM_16_Symbol_Mapping_4
    USE ENTITY work.qam_mapping_src_QAM_16_Symbol_Mapping_4(rtl);

  FOR ALL : qam_mapping_src_QAM_16_Symbol_Mapping_5
    USE ENTITY work.qam_mapping_src_QAM_16_Symbol_Mapping_5(rtl);

  FOR ALL : qam_mapping_src_QAM_16_Symbol_Mapping_6
    USE ENTITY work.qam_mapping_src_QAM_16_Symbol_Mapping_6(rtl);

  FOR ALL : qam_mapping_src_QAM_16_Symbol_Mapping_7
    USE ENTITY work.qam_mapping_src_QAM_16_Symbol_Mapping_7(rtl);

  FOR ALL : qam_mapping_src_QAM_16_Symbol_Mapping_8
    USE ENTITY work.qam_mapping_src_QAM_16_Symbol_Mapping_8(rtl);

  FOR ALL : qam_mapping_src_QAM_16_Symbol_Mapping_9
    USE ENTITY work.qam_mapping_src_QAM_16_Symbol_Mapping_9(rtl);

  FOR ALL : qam_mapping_src_QAM_16_Symbol_Mapping_10
    USE ENTITY work.qam_mapping_src_QAM_16_Symbol_Mapping_10(rtl);

  FOR ALL : qam_mapping_src_QAM_16_Symbol_Mapping_11
    USE ENTITY work.qam_mapping_src_QAM_16_Symbol_Mapping_11(rtl);

  FOR ALL : qam_mapping_src_QAM_16_Symbol_Mapping_12
    USE ENTITY work.qam_mapping_src_QAM_16_Symbol_Mapping_12(rtl);

  FOR ALL : qam_mapping_src_QAM_16_Symbol_Mapping_13
    USE ENTITY work.qam_mapping_src_QAM_16_Symbol_Mapping_13(rtl);

  FOR ALL : qam_mapping_src_QAM_16_Symbol_Mapping_14
    USE ENTITY work.qam_mapping_src_QAM_16_Symbol_Mapping_14(rtl);

  FOR ALL : qam_mapping_src_QAM_16_Symbol_Mapping_15
    USE ENTITY work.qam_mapping_src_QAM_16_Symbol_Mapping_15(rtl);

  -- Signals
  SIGNAL QAM_16_Symbol_Mapping_0_out1     : std_logic_vector(2 DOWNTO 0);  -- ufix3
  SIGNAL QAM_16_Symbol_Mapping_0_out1_signed : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL QAM_16_Symbol_Mapping_1_out1     : std_logic_vector(2 DOWNTO 0);  -- ufix3
  SIGNAL QAM_16_Symbol_Mapping_1_out1_signed : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL QAM_16_Symbol_Mapping_2_out1     : std_logic_vector(2 DOWNTO 0);  -- ufix3
  SIGNAL QAM_16_Symbol_Mapping_2_out1_signed : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL QAM_16_Symbol_Mapping_3_out1     : std_logic_vector(2 DOWNTO 0);  -- ufix3
  SIGNAL QAM_16_Symbol_Mapping_3_out1_signed : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL QAM_16_Symbol_Mapping_4_out1     : std_logic_vector(2 DOWNTO 0);  -- ufix3
  SIGNAL QAM_16_Symbol_Mapping_4_out1_signed : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL QAM_16_Symbol_Mapping_5_out1     : std_logic_vector(2 DOWNTO 0);  -- ufix3
  SIGNAL QAM_16_Symbol_Mapping_5_out1_signed : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL QAM_16_Symbol_Mapping_6_out1     : std_logic_vector(2 DOWNTO 0);  -- ufix3
  SIGNAL QAM_16_Symbol_Mapping_6_out1_signed : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL QAM_16_Symbol_Mapping_7_out1     : std_logic_vector(2 DOWNTO 0);  -- ufix3
  SIGNAL QAM_16_Symbol_Mapping_7_out1_signed : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL QAM_16_Symbol_Mapping_8_out1     : std_logic_vector(2 DOWNTO 0);  -- ufix3
  SIGNAL QAM_16_Symbol_Mapping_8_out1_signed : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL QAM_16_Symbol_Mapping_9_out1     : std_logic_vector(2 DOWNTO 0);  -- ufix3
  SIGNAL QAM_16_Symbol_Mapping_9_out1_signed : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL QAM_16_Symbol_Mapping_10_out1    : std_logic_vector(2 DOWNTO 0);  -- ufix3
  SIGNAL QAM_16_Symbol_Mapping_10_out1_signed : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL QAM_16_Symbol_Mapping_11_out1    : std_logic_vector(2 DOWNTO 0);  -- ufix3
  SIGNAL QAM_16_Symbol_Mapping_11_out1_signed : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL QAM_16_Symbol_Mapping_12_out1    : std_logic_vector(2 DOWNTO 0);  -- ufix3
  SIGNAL QAM_16_Symbol_Mapping_12_out1_signed : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL QAM_16_Symbol_Mapping_13_out1    : std_logic_vector(2 DOWNTO 0);  -- ufix3
  SIGNAL QAM_16_Symbol_Mapping_13_out1_signed : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL QAM_16_Symbol_Mapping_14_out1    : std_logic_vector(2 DOWNTO 0);  -- ufix3
  SIGNAL QAM_16_Symbol_Mapping_14_out1_signed : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL QAM_16_Symbol_Mapping_15_out1    : std_logic_vector(2 DOWNTO 0);  -- ufix3
  SIGNAL QAM_16_Symbol_Mapping_15_out1_signed : signed(2 DOWNTO 0);  -- sfix3
  SIGNAL concat_out1                      : unsigned(47 DOWNTO 0);  -- ufix48

BEGIN
  u_QAM_16_Symbol_Mapping_0 : qam_mapping_src_QAM_16_Symbol_Mapping_0
    PORT MAP( bits => bits,  -- ufix64
              Q => QAM_16_Symbol_Mapping_0_out1  -- sfix3
              );

  u_QAM_16_Symbol_Mapping_1 : qam_mapping_src_QAM_16_Symbol_Mapping_1
    PORT MAP( bits => bits,  -- ufix64
              Q => QAM_16_Symbol_Mapping_1_out1  -- sfix3
              );

  u_QAM_16_Symbol_Mapping_2 : qam_mapping_src_QAM_16_Symbol_Mapping_2
    PORT MAP( bits => bits,  -- ufix64
              Q => QAM_16_Symbol_Mapping_2_out1  -- sfix3
              );

  u_QAM_16_Symbol_Mapping_3 : qam_mapping_src_QAM_16_Symbol_Mapping_3
    PORT MAP( bits => bits,  -- ufix64
              Q => QAM_16_Symbol_Mapping_3_out1  -- sfix3
              );

  u_QAM_16_Symbol_Mapping_4 : qam_mapping_src_QAM_16_Symbol_Mapping_4
    PORT MAP( bits => bits,  -- ufix64
              Q => QAM_16_Symbol_Mapping_4_out1  -- sfix3
              );

  u_QAM_16_Symbol_Mapping_5 : qam_mapping_src_QAM_16_Symbol_Mapping_5
    PORT MAP( bits => bits,  -- ufix64
              Q => QAM_16_Symbol_Mapping_5_out1  -- sfix3
              );

  u_QAM_16_Symbol_Mapping_6 : qam_mapping_src_QAM_16_Symbol_Mapping_6
    PORT MAP( bits => bits,  -- ufix64
              Q => QAM_16_Symbol_Mapping_6_out1  -- sfix3
              );

  u_QAM_16_Symbol_Mapping_7 : qam_mapping_src_QAM_16_Symbol_Mapping_7
    PORT MAP( bits => bits,  -- ufix64
              Q => QAM_16_Symbol_Mapping_7_out1  -- sfix3
              );

  u_QAM_16_Symbol_Mapping_8 : qam_mapping_src_QAM_16_Symbol_Mapping_8
    PORT MAP( bits => bits,  -- ufix64
              Q => QAM_16_Symbol_Mapping_8_out1  -- sfix3
              );

  u_QAM_16_Symbol_Mapping_9 : qam_mapping_src_QAM_16_Symbol_Mapping_9
    PORT MAP( bits => bits,  -- ufix64
              Q => QAM_16_Symbol_Mapping_9_out1  -- sfix3
              );

  u_QAM_16_Symbol_Mapping_10 : qam_mapping_src_QAM_16_Symbol_Mapping_10
    PORT MAP( bits => bits,  -- ufix64
              Q => QAM_16_Symbol_Mapping_10_out1  -- sfix3
              );

  u_QAM_16_Symbol_Mapping_11 : qam_mapping_src_QAM_16_Symbol_Mapping_11
    PORT MAP( bits => bits,  -- ufix64
              Q => QAM_16_Symbol_Mapping_11_out1  -- sfix3
              );

  u_QAM_16_Symbol_Mapping_12 : qam_mapping_src_QAM_16_Symbol_Mapping_12
    PORT MAP( bits => bits,  -- ufix64
              Q => QAM_16_Symbol_Mapping_12_out1  -- sfix3
              );

  u_QAM_16_Symbol_Mapping_13 : qam_mapping_src_QAM_16_Symbol_Mapping_13
    PORT MAP( bits => bits,  -- ufix64
              Q => QAM_16_Symbol_Mapping_13_out1  -- sfix3
              );

  u_QAM_16_Symbol_Mapping_14 : qam_mapping_src_QAM_16_Symbol_Mapping_14
    PORT MAP( bits => bits,  -- ufix64
              Q => QAM_16_Symbol_Mapping_14_out1  -- sfix3
              );

  u_QAM_16_Symbol_Mapping_15 : qam_mapping_src_QAM_16_Symbol_Mapping_15
    PORT MAP( bits => bits,  -- ufix64
              Q => QAM_16_Symbol_Mapping_15_out1  -- sfix3
              );

  QAM_16_Symbol_Mapping_0_out1_signed <= signed(QAM_16_Symbol_Mapping_0_out1);

  QAM_16_Symbol_Mapping_1_out1_signed <= signed(QAM_16_Symbol_Mapping_1_out1);

  QAM_16_Symbol_Mapping_2_out1_signed <= signed(QAM_16_Symbol_Mapping_2_out1);

  QAM_16_Symbol_Mapping_3_out1_signed <= signed(QAM_16_Symbol_Mapping_3_out1);

  QAM_16_Symbol_Mapping_4_out1_signed <= signed(QAM_16_Symbol_Mapping_4_out1);

  QAM_16_Symbol_Mapping_5_out1_signed <= signed(QAM_16_Symbol_Mapping_5_out1);

  QAM_16_Symbol_Mapping_6_out1_signed <= signed(QAM_16_Symbol_Mapping_6_out1);

  QAM_16_Symbol_Mapping_7_out1_signed <= signed(QAM_16_Symbol_Mapping_7_out1);

  QAM_16_Symbol_Mapping_8_out1_signed <= signed(QAM_16_Symbol_Mapping_8_out1);

  QAM_16_Symbol_Mapping_9_out1_signed <= signed(QAM_16_Symbol_Mapping_9_out1);

  QAM_16_Symbol_Mapping_10_out1_signed <= signed(QAM_16_Symbol_Mapping_10_out1);

  QAM_16_Symbol_Mapping_11_out1_signed <= signed(QAM_16_Symbol_Mapping_11_out1);

  QAM_16_Symbol_Mapping_12_out1_signed <= signed(QAM_16_Symbol_Mapping_12_out1);

  QAM_16_Symbol_Mapping_13_out1_signed <= signed(QAM_16_Symbol_Mapping_13_out1);

  QAM_16_Symbol_Mapping_14_out1_signed <= signed(QAM_16_Symbol_Mapping_14_out1);

  QAM_16_Symbol_Mapping_15_out1_signed <= signed(QAM_16_Symbol_Mapping_15_out1);

  concat_out1 <= unsigned(QAM_16_Symbol_Mapping_0_out1_signed) & unsigned(QAM_16_Symbol_Mapping_1_out1_signed) & unsigned(QAM_16_Symbol_Mapping_2_out1_signed) & unsigned(QAM_16_Symbol_Mapping_3_out1_signed) & unsigned(QAM_16_Symbol_Mapping_4_out1_signed) & unsigned(QAM_16_Symbol_Mapping_5_out1_signed) & unsigned(QAM_16_Symbol_Mapping_6_out1_signed) & unsigned(QAM_16_Symbol_Mapping_7_out1_signed) & unsigned(QAM_16_Symbol_Mapping_8_out1_signed) & unsigned(QAM_16_Symbol_Mapping_9_out1_signed) & unsigned(QAM_16_Symbol_Mapping_10_out1_signed) & unsigned(QAM_16_Symbol_Mapping_11_out1_signed) & unsigned(QAM_16_Symbol_Mapping_12_out1_signed) & unsigned(QAM_16_Symbol_Mapping_13_out1_signed) & unsigned(QAM_16_Symbol_Mapping_14_out1_signed) & unsigned(QAM_16_Symbol_Mapping_15_out1_signed);

  symbol <= std_logic_vector(concat_out1);

END rtl;

