-- -------------------------------------------------------------
-- 
-- File Name: hdl_32bits\hdlsrc\fec_ber_hw_V2\random_number_generator_src_tvalid_hold.vhd
-- Created: 2022-10-27 12:01:58
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: random_number_generator_src_tvalid_hold
-- Source Path: fec_ber_hw_V2/Random Number Generator/tvalid hold
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY random_number_generator_src_tvalid_hold IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_4_0                         :   IN    std_logic;
        trigger                           :   IN    std_logic;
        comparator                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        enable                            :   OUT   std_logic;
        diff                              :   OUT   std_logic_vector(32 DOWNTO 0)  -- sfix33
        );
END random_number_generator_src_tvalid_hold;


ARCHITECTURE rtl OF random_number_generator_src_tvalid_hold IS

  -- Signals
  SIGNAL comparator_unsigned              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Multiport_Switch_out1            : std_logic;
  SIGNAL Delay2_out1                      : std_logic;
  SIGNAL Equal_relop1                     : std_logic;
  SIGNAL HDL_Counter_out1                 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL OR_out1                          : std_logic;
  SIGNAL Subtract_sub_cast                : signed(32 DOWNTO 0);  -- sfix33
  SIGNAL Subtract_sub_cast_1              : signed(32 DOWNTO 0);  -- sfix33
  SIGNAL Subtract_out1                    : signed(32 DOWNTO 0);  -- sfix33

BEGIN
  comparator_unsigned <= unsigned(comparator);

  Delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay2_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_4_0 = '1' THEN
        Delay2_out1 <= Multiport_Switch_out1;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  -- Free running, Unsigned Counter
  --  initial value   = 0
  --  step value      = 32
  HDL_Counter_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_4_0 = '1' THEN
        IF Equal_relop1 = '1' THEN 
          HDL_Counter_out1 <= to_unsigned(0, 32);
        ELSIF Multiport_Switch_out1 = '1' THEN 
          HDL_Counter_out1 <= HDL_Counter_out1 + to_unsigned(32, 32);
        END IF;
      END IF;
    END IF;
  END PROCESS HDL_Counter_process;


  
  Equal_relop1 <= '1' WHEN HDL_Counter_out1 >= comparator_unsigned ELSE
      '0';

  OR_out1 <= Equal_relop1 OR trigger;

  
  Multiport_Switch_out1 <= Delay2_out1 WHEN OR_out1 = '0' ELSE
      trigger;

  Subtract_sub_cast <= signed(resize(HDL_Counter_out1, 33));
  Subtract_sub_cast_1 <= signed(resize(comparator_unsigned, 33));
  Subtract_out1 <= Subtract_sub_cast - Subtract_sub_cast_1;

  diff <= std_logic_vector(Subtract_out1);

  enable <= Multiport_Switch_out1;

END rtl;

