-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\fec_ber_hw\soft_demodulation_src_sign_extend.vhd
-- Created: 2022-10-06 15:14:46
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: soft_demodulation_src_sign_extend
-- Source Path: fec_ber_hw/Soft Demodulation/sign_extend
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY soft_demodulation_src_sign_extend IS
  PORT( u                                 :   IN    std_logic_vector(5 DOWNTO 0);  -- sfix6_En2
        y                                 :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END soft_demodulation_src_sign_extend;


ARCHITECTURE rtl OF soft_demodulation_src_sign_extend IS

  -- Signals
  SIGNAL u_signed                         : signed(5 DOWNTO 0);  -- sfix6_En2
  SIGNAL Bit_Slice_out1                   : std_logic;  -- ufix1
  SIGNAL Bit_Concat_out1                  : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  u_signed <= signed(u);

  Bit_Slice_out1 <= u_signed(5);

  Bit_Concat_out1 <= Bit_Slice_out1 & Bit_Slice_out1 & unsigned(u_signed);

  y <= std_logic_vector(Bit_Concat_out1);

END rtl;

