-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\book_example_v2\Random_Number_Gen_dut.vhd
-- Created: 2023-01-13 11:55:54
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Random_Number_Gen_dut
-- Source Path: Random_Number_Gen/Random_Number_Gen_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Random_Number_Gen_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        aximm_enable                      :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        aximm_bits                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        aximm_reset                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        m00_axis_tready                   :   IN    std_logic;  -- ufix1
        ce_out                            :   OUT   std_logic;  -- ufix1
        m00_axis_tvalid                   :   OUT   std_logic;  -- ufix1
        m00_axis_tdata                    :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
        m01_axis_tvalid                   :   OUT   std_logic;  -- ufix1
        m01_axis_tdata                    :   OUT   std_logic_vector(7 DOWNTO 0)  -- ufix8
        );
END Random_Number_Gen_dut;


ARCHITECTURE rtl OF Random_Number_Gen_dut IS

  -- Component Declarations
  COMPONENT Random_Number_Gen_src_Random_Number_Generator
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          aximm_enable                    :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          aximm_bits                      :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          aximm_reset                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          m00_axis_tready                 :   IN    std_logic;  -- ufix1
          ce_out                          :   OUT   std_logic;  -- ufix1
          m00_axis_tvalid                 :   OUT   std_logic;  -- ufix1
          m00_axis_tdata                  :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
          m01_axis_tvalid                 :   OUT   std_logic;  -- ufix1
          m01_axis_tdata                  :   OUT   std_logic_vector(7 DOWNTO 0)  -- ufix8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Random_Number_Gen_src_Random_Number_Generator
    USE ENTITY work.Random_Number_Gen_src_Random_Number_Generator(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL m00_axis_tready_sig              : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL m00_axis_tvalid_sig              : std_logic;  -- ufix1
  SIGNAL m00_axis_tdata_sig               : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL m01_axis_tvalid_sig              : std_logic;  -- ufix1
  SIGNAL m01_axis_tdata_sig               : std_logic_vector(7 DOWNTO 0);  -- ufix8

BEGIN
  u_Random_Number_Gen_src_Random_Number_Generator : Random_Number_Gen_src_Random_Number_Generator
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              aximm_enable => aximm_enable,  -- ufix32
              aximm_bits => aximm_bits,  -- ufix32
              aximm_reset => aximm_reset,  -- ufix32
              m00_axis_tready => m00_axis_tready_sig,  -- ufix1
              ce_out => ce_out_sig,  -- ufix1
              m00_axis_tvalid => m00_axis_tvalid_sig,  -- ufix1
              m00_axis_tdata => m00_axis_tdata_sig,  -- ufix8
              m01_axis_tvalid => m01_axis_tvalid_sig,  -- ufix1
              m01_axis_tdata => m01_axis_tdata_sig  -- ufix8
              );

  m00_axis_tready_sig <= m00_axis_tready;

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  m00_axis_tvalid <= m00_axis_tvalid_sig;

  m00_axis_tdata <= m00_axis_tdata_sig;

  m01_axis_tvalid <= m01_axis_tvalid_sig;

  m01_axis_tdata <= m01_axis_tdata_sig;

END rtl;

