-- -------------------------------------------------------------
-- 
-- File Name: hdl_32bit\hdlsrc\fec_ber_hw_V2\encoder_control_src_Encoder_Ctrl.vhd
-- Created: 2022-10-27 12:29:33
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1.5625e-09
-- Target subsystem base rate: 6.25e-09
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        6.25e-09
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- m_axis_ctrl_tvalid            ce_out        6.25e-09
-- m_axis_ctrl_tdata             ce_out        6.25e-09
-- m_axis_ctrl_tlast             ce_out        6.25e-09
-- m_axis_tvalid                 ce_out        6.25e-09
-- m_axis_tdata                  ce_out        6.25e-09
-- s_axis_status_tready          ce_out        6.25e-09
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: encoder_control_src_Encoder_Ctrl
-- Source Path: fec_ber_hw_V2/Encoder Ctrl
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY encoder_control_src_Encoder_Ctrl IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        aximm_ctrl_word                   :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        aximm_length                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        aximm_load                        :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        s_axis_tvalid                     :   IN    std_logic;
        s_axis_tdata                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        s_axis_status_tvalid              :   IN    std_logic;
        s_axis_status_tdata               :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        m_axis_ctrl_tvalid                :   OUT   std_logic;
        m_axis_ctrl_tdata                 :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        m_axis_ctrl_tlast                 :   OUT   std_logic;
        m_axis_tvalid                     :   OUT   std_logic;
        m_axis_tdata                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        s_axis_status_tready              :   OUT   std_logic
        );
END encoder_control_src_Encoder_Ctrl;


ARCHITECTURE rtl OF encoder_control_src_Encoder_Ctrl IS

  -- Component Declarations
  COMPONENT encoder_control_src_Rising_Edge
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_4_0                       :   IN    std_logic;
          In1                             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Out1                            :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT encoder_control_src_Chart
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_4_0                       :   IN    std_logic;
          ctrl_word                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          block_length                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          load                            :   IN    std_logic;
          s_axis_tvalid                   :   IN    std_logic;
          s_axis_tdata                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          m_axis_ctrl_tvalid              :   OUT   std_logic;
          m_axis_ctrl_tdata               :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          m_axis_ctrl_tlast               :   OUT   std_logic;
          m_axis_tvalid                   :   OUT   std_logic;
          s_axis_status_tready            :   OUT   std_logic;
          m_axis_tdata                    :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : encoder_control_src_Rising_Edge
    USE ENTITY work.encoder_control_src_Rising_Edge(rtl);

  FOR ALL : encoder_control_src_Chart
    USE ENTITY work.encoder_control_src_Chart(rtl);

  -- Signals
  SIGNAL enb_1_4_0                        : std_logic;
  SIGNAL Rising_Edge_out1                 : std_logic;
  SIGNAL m_axis_ctrl_tdata_tmp            : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL m_axis_tvalid_1                  : std_logic;
  SIGNAL m_axis_tdata_1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Delay_out1                       : std_logic;
  SIGNAL m_axis_tdata_unsigned            : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Delay1_out1                      : unsigned(31 DOWNTO 0);  -- uint32

BEGIN
  u_Rising_Edge : encoder_control_src_Rising_Edge
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_4_0 => clk_enable,
              In1 => aximm_load,  -- uint32
              Out1 => Rising_Edge_out1
              );

  u_Chart : encoder_control_src_Chart
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_4_0 => clk_enable,
              ctrl_word => aximm_ctrl_word,  -- uint32
              block_length => aximm_length,  -- uint32
              load => Rising_Edge_out1,
              s_axis_tvalid => s_axis_tvalid,
              s_axis_tdata => s_axis_tdata,  -- uint32
              m_axis_ctrl_tvalid => m_axis_ctrl_tvalid,
              m_axis_ctrl_tdata => m_axis_ctrl_tdata_tmp,  -- uint32
              m_axis_ctrl_tlast => m_axis_ctrl_tlast,
              m_axis_tvalid => m_axis_tvalid_1,
              s_axis_status_tready => s_axis_status_tready,
              m_axis_tdata => m_axis_tdata_1  -- uint32
              );

  enb_1_4_0 <= clk_enable;

  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_4_0 = '1' THEN
        Delay_out1 <= m_axis_tvalid_1;
      END IF;
    END IF;
  END PROCESS Delay_process;


  m_axis_tdata_unsigned <= unsigned(m_axis_tdata_1);

  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_out1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_4_0 = '1' THEN
        Delay1_out1 <= m_axis_tdata_unsigned;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  m_axis_tdata <= std_logic_vector(Delay1_out1);

  ce_out <= clk_enable;

  m_axis_ctrl_tdata <= m_axis_ctrl_tdata_tmp;

  m_axis_tvalid <= Delay_out1;

END rtl;

