-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\fec_ber_hw\qam_mapping_src_sample_and_hold_block.vhd
-- Created: 2022-10-06 15:06:34
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: qam_mapping_src_sample_and_hold_block
-- Source Path: fec_ber_hw/QAM Mapping/sample_and_hold
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY qam_mapping_src_sample_and_hold_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        valid_in                          :   IN    std_logic;
        data_in                           :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        alphavalid_out                    :   OUT   std_logic;
        alphadata_out                     :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END qam_mapping_src_sample_and_hold_block;


ARCHITECTURE rtl OF qam_mapping_src_sample_and_hold_block IS

  -- Component Declarations
  COMPONENT qam_mapping_src_tvalid_hold
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1                             :   IN    std_logic;
          alpha                           :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT qam_mapping_src_Sample_and_Hold
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In_rsvd                         :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          Trigger                         :   IN    std_logic;
          alpha                           :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : qam_mapping_src_tvalid_hold
    USE ENTITY work.qam_mapping_src_tvalid_hold(rtl);

  FOR ALL : qam_mapping_src_Sample_and_Hold
    USE ENTITY work.qam_mapping_src_Sample_and_Hold(rtl);

  -- Signals
  SIGNAL tvalid_hold_out1                 : std_logic;
  SIGNAL Sample_and_Hold_out1             : std_logic_vector(7 DOWNTO 0);  -- ufix8

BEGIN
  u_tvalid_hold : qam_mapping_src_tvalid_hold
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1 => valid_in,
              alpha => tvalid_hold_out1
              );

  u_Sample_and_Hold : qam_mapping_src_Sample_and_Hold
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In_rsvd => data_in,  -- uint8
              Trigger => valid_in,
              alpha => Sample_and_Hold_out1  -- uint8
              );

  alphavalid_out <= tvalid_hold_out1;

  alphadata_out <= Sample_and_Hold_out1;

END rtl;

