-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\fec_ber_hw\soft_demodulation_dut.vhd
-- Created: 2022-10-06 15:14:51
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: soft_demodulation_dut
-- Source Path: soft_demodulation/soft_demodulation_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY soft_demodulation_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        aximm_llr_scale                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32_En22
        aximm_llr_mag_reset               :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        s_axis_tvalid                     :   IN    std_logic;  -- ufix1
        s_axis_tdata                      :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        ce_out                            :   OUT   std_logic;  -- ufix1
        aximm_llr_max                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32_En24
        m_axis_tvalid                     :   OUT   std_logic;  -- ufix1
        m_axis_tdata                      :   OUT   std_logic_vector(7 DOWNTO 0)  -- ufix8
        );
END soft_demodulation_dut;


ARCHITECTURE rtl OF soft_demodulation_dut IS

  -- Component Declarations
  COMPONENT soft_demodulation_src_Soft_Demodulation
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          aximm_llr_scale                 :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32_En22
          aximm_llr_mag_reset             :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          s_axis_tvalid                   :   IN    std_logic;  -- ufix1
          s_axis_tdata                    :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          ce_out                          :   OUT   std_logic;  -- ufix1
          aximm_llr_max                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32_En24
          m_axis_tvalid                   :   OUT   std_logic;  -- ufix1
          m_axis_tdata                    :   OUT   std_logic_vector(7 DOWNTO 0)  -- ufix8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : soft_demodulation_src_Soft_Demodulation
    USE ENTITY work.soft_demodulation_src_Soft_Demodulation(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL s_axis_tvalid_sig                : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL aximm_llr_max_sig                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL m_axis_tvalid_sig                : std_logic;  -- ufix1
  SIGNAL m_axis_tdata_sig                 : std_logic_vector(7 DOWNTO 0);  -- ufix8

BEGIN
  u_soft_demodulation_src_Soft_Demodulation : soft_demodulation_src_Soft_Demodulation
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              aximm_llr_scale => aximm_llr_scale,  -- ufix32_En22
              aximm_llr_mag_reset => aximm_llr_mag_reset,  -- ufix32
              s_axis_tvalid => s_axis_tvalid_sig,  -- ufix1
              s_axis_tdata => s_axis_tdata,  -- ufix32
              ce_out => ce_out_sig,  -- ufix1
              aximm_llr_max => aximm_llr_max_sig,  -- ufix32_En24
              m_axis_tvalid => m_axis_tvalid_sig,  -- ufix1
              m_axis_tdata => m_axis_tdata_sig  -- ufix8
              );

  s_axis_tvalid_sig <= s_axis_tvalid;

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  aximm_llr_max <= aximm_llr_max_sig;

  m_axis_tvalid <= m_axis_tvalid_sig;

  m_axis_tdata <= m_axis_tdata_sig;

END rtl;

