-- -------------------------------------------------------------
-- 
-- File Name: hdl_32bits\hdlsrc\fec_ber_hw_V2\decoder_control_src_Rising_Edge.vhd
-- Created: 2022-10-27 15:30:16
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: decoder_control_src_Rising_Edge
-- Source Path: fec_ber_hw_V2/FEC Ctrl/Rising Edge
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY decoder_control_src_Rising_Edge IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In1                               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Out1                              :   OUT   std_logic
        );
END decoder_control_src_Rising_Edge;


ARCHITECTURE rtl OF decoder_control_src_Rising_Edge IS

  -- Signals
  SIGNAL In1_unsigned                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Data_Type_Conversion1_out1       : std_logic;
  SIGNAL Delay2_out1                      : std_logic;
  SIGNAL Logical_Operator_out1            : std_logic;
  SIGNAL Logical_Operator1_out1           : std_logic;

BEGIN
  In1_unsigned <= unsigned(In1);

  
  Data_Type_Conversion1_out1 <= '1' WHEN In1_unsigned /= to_unsigned(0, 32) ELSE
      '0';

  Delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay2_out1 <= '1';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay2_out1 <= Data_Type_Conversion1_out1;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  Logical_Operator_out1 <=  NOT Delay2_out1;

  Logical_Operator1_out1 <= Data_Type_Conversion1_out1 AND Logical_Operator_out1;

  Out1 <= Logical_Operator1_out1;

END rtl;

